### PR TITLE
Template and Organization Selection Feature

### PR DESCRIPTION
**Pull request by HongSenDu**
Added in feature to write to either the graphicsdesk or newsdev organization as well as select templates

### CODE REVIEW

**Review by squirrelsquirrel78 — CHANGES_REQUESTED** [review]
yeet

## Small things

### Org selection

Right now the user prompt is:
```
Please choose an github to clone from
1. graphicsdesk
2. NewsroomDevelopment
? Please input your selection: (Input a number)
```

Can we condense this to:
```
? Please choose an organization: ("1" for graphicsdesk, "2" for NewsroomDevelopment)
```

Or, we could ask people to, instead of using spectate clone like `spectate clone <repository-name>`, do `spectate clone <org-name>/<repo-name>`. Not sure which one's easier for ppl. Water ur thoughts?

### really small things
* in constants.js, remove the use of one-time variables (e.g. instead of having `templates`, just do `templates: ['default', ...`.

**Review by squirrelsquirrel78 — CHANGES_REQUESTED** [review]
## Templates

What would you say is the approximate proportion of stories that use `series` ? If you think that proportion is low, I'm tempted to suggest that we use a flag to choose templates instead of user input. For instance:
<pre>
$ spectate create [-t <ins>template_name</ins>]
</pre>

Aside from this, I think the last thing that's left to do is from [here](https://github.com/graphicsdesk/spectate/pull/21#issuecomment-778649421): Creating a `series` template should be implemented as creating a `default` template and then copying over some series files.

## Organizations

image
Remove the redundant "Please choose an github organization".

**Comment by HongSenDu** [comment]
I htink series has been like 30% of stories rn. Also a series template does first do default and then copy over those files

**Comment by squirrelsquirrel78** [comment]
Oh I did not notice haha, mb. Then I think the only changes left to do are the redundant comment from above. After this is merged, u shud add the organization stuff to documentation too

**Comment by squirrelsquirrel78** [comment]
yeet

**Pull request merged**
